output   = "models"
wipe     = true
no-tests = true

[psql]
  blacklist = ["schema_migrations"]

[[types]]
  [types.match]
    db_type = "uuid"

  [types.replace]
    type = "uuid.UUID"

  [types.imports]
    third_party = ['"github.com/google/uuid"']
