// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Lol   string
	Posts string
	Users string
	Wuut  string
}{
	Lol:   "lol",
	Posts: "posts",
	Users: "users",
	Wuut:  "wuut",
}
